{"url":"https://api.github.com/repos/owncloud/core/issues/2916","labels_url":"https://api.github.com/repos/owncloud/core/issues/2916/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/2916/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/2916/events","html_url":"https://github.com/owncloud/core/issues/2916","id":13156980,"number":2916,"title":"update from 5.03 to 5.0.4 throws error because of non-relevant table in database","user":{"login":"erolha","id":4114299,"avatar_url":"https://gravatar.com/avatar/d9a6984a4cdd8a7b34c875fc3b8a05e8?d=https%3a%2f%2fidenticons.github.com%2f00d162d98fbd0db485d30d832d39ba36.png&r=x","gravatar_id":"d9a6984a4cdd8a7b34c875fc3b8a05e8","url":"https://api.github.com/users/erolha","html_url":"https://github.com/erolha","followers_url":"https://api.github.com/users/erolha/followers","following_url":"https://api.github.com/users/erolha/following{/other_user}","gists_url":"https://api.github.com/users/erolha/gists{/gist_id}","starred_url":"https://api.github.com/users/erolha/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/erolha/subscriptions","organizations_url":"https://api.github.com/users/erolha/orgs","repos_url":"https://api.github.com/users/erolha/repos","events_url":"https://api.github.com/users/erolha/events{/privacy}","received_events_url":"https://api.github.com/users/erolha/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/update","name":"update","color":"e10c02"}],"state":"closed","assignee":{"login":"deepdiver1975","id":1005065,"avatar_url":"https://gravatar.com/avatar/bdba071ed68da9ce8edae53c364902ef?d=https%3a%2f%2fidenticons.github.com%2f67e101ad9531b7d25697b76e503e062e.png&r=x","gravatar_id":"bdba071ed68da9ce8edae53c364902ef","url":"https://api.github.com/users/deepdiver1975","html_url":"https://github.com/deepdiver1975","followers_url":"https://api.github.com/users/deepdiver1975/followers","following_url":"https://api.github.com/users/deepdiver1975/following{/other_user}","gists_url":"https://api.github.com/users/deepdiver1975/gists{/gist_id}","starred_url":"https://api.github.com/users/deepdiver1975/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/deepdiver1975/subscriptions","organizations_url":"https://api.github.com/users/deepdiver1975/orgs","repos_url":"https://api.github.com/users/deepdiver1975/repos","events_url":"https://api.github.com/users/deepdiver1975/events{/privacy}","received_events_url":"https://api.github.com/users/deepdiver1975/received_events","type":"user","site_admin":false},"milestone":null,"comments":3,"created_at":"2013-04-13t14:16:08z","updated_at":"2013-07-12t16:08:45z","closed_at":"2013-07-12t16:08:45z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"### expected behaviour\r\nsmooth upgrade of clean (with only the admin-user) 5.0.3 installation to 5.0.4\r\n\r\n### actual behaviour\r\nturned on maintenance mode\r\nfailed to get existing database structure for updating (mdb2_schema error: schema validation error, there was already an primary index or autoincrement field in \"ow_base_question_account_type\" before \"primary\")\r\n\r\n### steps to reproduce\r\n1. have my database\r\n2. install oc 5.0.3\r\n3. update to 5.0.4\r\n\r\n### server configuration\r\noperating system: ubuntu 12.04 2 (64)\r\n\r\nweb server: apache/2.2.22\r\n\r\ndatabase: mysql ver 14.14 distrib 5.5.29, for debian-linux-gnu (x86_64) using readline 6.2\r\n\r\nphp version: php 5.3.10-1ubuntu3.6 with suhosin-patc\r\n\r\nowncloud version: 5.0.4\r\n\r\n\r\n#### owncloud log (data/owncloud.log)\r\n```\r\n    {\"app\":\"php\",\"message\":\"non-static method mdb2_schema::errormessage() should not be called statically, assuming $this from incompatible context at \\/var\\/www\\/...\\/...\\/3rdparty\\/mdb2\\/schema.php#2794\",\"level\":2,\"time\":1365703262}\r\n    {\"app\":\"core\",\"message\":\"failed to get existing database structure for updating (mdb2_schema error: schema validation error, there was already an primary index or autoincrement field in \\\"ow_base_question_account_type\\\" before \\\"primary\\\")\",\"level\":4,\"time\":1365703262}\r\n\r\n##############\r\nwhat's special here is that the (mysql) tables was also newly created for the 5.0.3, with default (hardcoded -why?) oc_ prefix. (look at the error in the log. it refers to a table with ow_.)\r\n\r\ni solved the problem by moving owncloud to it's own database, but i'm still curious about how this can happen.","closed_by":{"login":"vicdeo","id":991300,"avatar_url":"https://gravatar.com/avatar/57b8c1e26d502d5414e4b2fb875d2994?d=https%3a%2f%2fidenticons.github.com%2fe8357fefe8bad5436de368fa5a419461.png&r=x","gravatar_id":"57b8c1e26d502d5414e4b2fb875d2994","url":"https://api.github.com/users/vicdeo","html_url":"https://github.com/vicdeo","followers_url":"https://api.github.com/users/vicdeo/followers","following_url":"https://api.github.com/users/vicdeo/following{/other_user}","gists_url":"https://api.github.com/users/vicdeo/gists{/gist_id}","starred_url":"https://api.github.com/users/vicdeo/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/vicdeo/subscriptions","organizations_url":"https://api.github.com/users/vicdeo/orgs","repos_url":"https://api.github.com/users/vicdeo/repos","events_url":"https://api.github.com/users/vicdeo/events{/privacy}","received_events_url":"https://api.github.com/users/vicdeo/received_events","type":"user","site_admin":false}}