{"url":"https://api.github.com/repos/owncloud/core/issues/2471","labels_url":"https://api.github.com/repos/owncloud/core/issues/2471/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/2471/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/2471/events","html_url":"https://github.com/owncloud/core/issues/2471","id":12217759,"number":2471,"title":"file deletion problems","user":{"login":"sciurius","id":1118804,"avatar_url":"https://gravatar.com/avatar/79732b7d3021152a70d3b4b4d6ad032f?d=https%3a%2f%2fidenticons.github.com%2f593511b47fe6e8b4979cf77215ed9c15.png&r=x","gravatar_id":"79732b7d3021152a70d3b4b4d6ad032f","url":"https://api.github.com/users/sciurius","html_url":"https://github.com/sciurius","followers_url":"https://api.github.com/users/sciurius/followers","following_url":"https://api.github.com/users/sciurius/following{/other_user}","gists_url":"https://api.github.com/users/sciurius/gists{/gist_id}","starred_url":"https://api.github.com/users/sciurius/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sciurius/subscriptions","organizations_url":"https://api.github.com/users/sciurius/orgs","repos_url":"https://api.github.com/users/sciurius/repos","events_url":"https://api.github.com/users/sciurius/events{/privacy}","received_events_url":"https://api.github.com/users/sciurius/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/bug","name":"bug","color":"fc2929"}],"state":"closed","assignee":null,"milestone":null,"comments":2,"created_at":"2013-03-20t08:58:15z","updated_at":"2013-03-20t09:34:47z","closed_at":"2013-03-20t09:34:47z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"when deleting a file using the files app, the file is removed but cannot be restored (apps/files_trashbin shows nothing to undelete).\r\nthe log shows an error:\r\n    error while running hook (oca\\\\files_trashbin\\\\hooks::remove_hook): sqlstate[42601]: syntax error: 7 error:  syntax error at or near \\\"user\\\"\\nline 1: ...o oc_files_trash (id,timestamp,location,type,mime,user) valu...\\n\r\n\r\nit turns out that postgresql does not allow 'user' as a column name in the insert list. changing this to \"user\" makes this error go away, but another error shows up:\r\n    error while running hook (oca\\\\files_trashbin\\\\hooks::remove_hook): sqlstate[42601]: syntax error: 7 error:  syntax error at or near \\\"user\\\"\\nline 1: insert into oc_files_trashsize (size, user) values ($1, $2)\\n\r\n\r\nwhen this error is fixed by inserting \" \" around the word user, no errors show up when removing a file, but it is still not possible to undelete removed files.\r\n\r\n**on a side note: i think it is very dangerous when errors like these go unnoticed. the user removes a file and sees nothing but apparent success. only when inspecting the log files these errors are noticed.**\r\n\r\nowncloud 5.0, system is fedora 17, postgresql 9.1.8.","closed_by":{"login":"schiesbn","id":1589737,"avatar_url":"https://gravatar.com/avatar/8912b598c7b32dd25b87fd168e0b06b2?d=https%3a%2f%2fidenticons.github.com%2f0a323047dbe8329db30eae8dbe96e55e.png&r=x","gravatar_id":"8912b598c7b32dd25b87fd168e0b06b2","url":"https://api.github.com/users/schiesbn","html_url":"https://github.com/schiesbn","followers_url":"https://api.github.com/users/schiesbn/followers","following_url":"https://api.github.com/users/schiesbn/following{/other_user}","gists_url":"https://api.github.com/users/schiesbn/gists{/gist_id}","starred_url":"https://api.github.com/users/schiesbn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schiesbn/subscriptions","organizations_url":"https://api.github.com/users/schiesbn/orgs","repos_url":"https://api.github.com/users/schiesbn/repos","events_url":"https://api.github.com/users/schiesbn/events{/privacy}","received_events_url":"https://api.github.com/users/schiesbn/received_events","type":"user","site_admin":false}}