{"url":"https://api.github.com/repos/owncloud/core/issues/243","labels_url":"https://api.github.com/repos/owncloud/core/issues/243/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/243/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/243/events","html_url":"https://github.com/owncloud/core/issues/243","id":8090573,"number":243,"title":"redirecting of /apps/contacts/carddav.php, /apps/calendar/caldav.php not working with separate apps-directory","user":{"login":"svolke","id":2721386,"avatar_url":"https://gravatar.com/avatar/3266028ae89bd76ef01e474c96b4d1b5?d=https%3a%2f%2fidenticons.github.com%2f0e2e2a8dcf4d6ba29b80639ea156e2e1.png&r=x","gravatar_id":"3266028ae89bd76ef01e474c96b4d1b5","url":"https://api.github.com/users/svolke","html_url":"https://github.com/svolke","followers_url":"https://api.github.com/users/svolke/followers","following_url":"https://api.github.com/users/svolke/following{/other_user}","gists_url":"https://api.github.com/users/svolke/gists{/gist_id}","starred_url":"https://api.github.com/users/svolke/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/svolke/subscriptions","organizations_url":"https://api.github.com/users/svolke/orgs","repos_url":"https://api.github.com/users/svolke/repos","events_url":"https://api.github.com/users/svolke/events{/privacy}","received_events_url":"https://api.github.com/users/svolke/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":22,"created_at":"2012-11-04t18:11:03z","updated_at":"2013-02-28t11:02:49z","closed_at":"2013-02-26t16:00:09z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"when checking out owncloud from the github repositories and having the apps repo in the apps2 directory,\r\nusing carddav and caldav via the \"old\" default uri /apps/contacts/carddav.php and /apps/calendar/caldav.php does not work.\r\ni get a sabredav-error:\r\n*    sabre_dav_exception_forbidden\r\n*    requested uri (/apps/contacts/carddav.php) is out of base uri (/remote.php/carddav/)\r\n\r\n\r\nsteps to reproduce:\r\n* have contacts app in apps directory.\r\n* access http://host/apps/contacts/carddav.php and http://host/remote.php/carddav\r\n* both work\r\n* now move the contacts app to apps2 directory\r\n* access http://host/apps2/contacts/carddav.php and http://host/remote.php/carddav\r\n* both work\r\n* access http://host/apps/contacts/carddav.php (e.g. via android app) -> redirect to http://host/remote.php/carddav happens internally, but: the above error is thrown","closed_by":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false}}