{"url":"https://api.github.com/repos/owncloud/core/issues/1310","labels_url":"https://api.github.com/repos/owncloud/core/issues/1310/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/1310/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/1310/events","html_url":"https://github.com/owncloud/core/issues/1310","id":10317994,"number":1310,"title":"error when creating a folder with name \"data\"","user":{"login":"erlison","id":3381529,"avatar_url":"https://gravatar.com/avatar/8fcafdaef2695ef8a3fc6005ef8cb4c2?d=https%3a%2f%2fidenticons.github.com%2f19e85f0460285625024a9b2984358e00.png&r=x","gravatar_id":"8fcafdaef2695ef8a3fc6005ef8cb4c2","url":"https://api.github.com/users/erlison","html_url":"https://github.com/erlison","followers_url":"https://api.github.com/users/erlison/followers","following_url":"https://api.github.com/users/erlison/following{/other_user}","gists_url":"https://api.github.com/users/erlison/gists{/gist_id}","starred_url":"https://api.github.com/users/erlison/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/erlison/subscriptions","organizations_url":"https://api.github.com/users/erlison/orgs","repos_url":"https://api.github.com/users/erlison/repos","events_url":"https://api.github.com/users/erlison/events{/privacy}","received_events_url":"https://api.github.com/users/erlison/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/bug","name":"bug","color":"fc2929"}],"state":"closed","assignee":null,"milestone":null,"comments":1,"created_at":"2013-01-25t16:55:18z","updated_at":"2013-02-09t16:11:47z","closed_at":"2013-02-09t16:11:47z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"the owncloud can not synchronize a folder with name \"data\". the access denied message is displayed in several log. i also tried to create the folder using remote.php / webdav but it still fails too.  the error also occurs on the owncloud client.\r\n\r\nsee the log below\r\n\r\n\r\nowncloud client.log\r\n01-25 12:51:20:565 oc_module: stating directory owncloud://192.168.0.105/owncloud/remote.php/webdav/documents/data/\r\n01-25 12:51:20:565 oc_module: owncloud_stat owncloud://192.168.0.105/owncloud/remote.php/webdav/documents/data/ called\r\n01-25 12:51:20:568 oc_module: request failed, don't take session header.\r\n01-25 12:51:20:568 oc_module: neon error code was 1\r\n01-25 12:51:20:568 oc_module: wrn: propfind named failed with 1, request error: 403 forbidden\r\n01-25 12:51:20:569 oc_module: => errno after fetch resource list for owncloud://192.168.0.105/owncloud/remote.php/webdav/documents/data/default: 22\r\n\r\napache error_log\r\nfri jan 25 14:00:07 2013] [error] [client 192.168.0.104] client denied by server configuration: /opt/share/www/owncloud/remote.php\r\n\r\napache access_log\r\n192.168.0.104 - - [25/jan/2013:14:00:04 -0200]  \"mkcol /owncloud/remote.php/webdav/documents/data/ http/1.1\" 403 277\r\n\r\nin mac os shell\r\n$curl --insecure --user user:password --request mkcol http://192.168.0.105/owncloud/remote.php/webdav/documents/data/\r\n\r\n<!doctype html public \"-//ietf//dtd html 2.0//en\">\r\n<html><head>\r\n<title>403 forbidden</title>\r\n</head><body>\r\n<h1>forbidden</h1>\r\n<p>you don't have permission to access /owncloud/remote.php/webdav/documentos/data/\r\non this server.</p>\r\n</body></html>\r\n\r\n\r\nowncloud 4.5.6\r\nowncloud client version 1.2.0beta2\r\n\r\n*** server\r\niomega ix2-200 cloud edition\r\nfirmware 3.2.6.21659\r\nlinux 2.6.31.8 armv5t4l\r\n\r\napache /2.2.20 (unix)\r\nphp 5.3.20 (cli)\r\n\r\n*** notebook\r\nmac os x 10.8.2\r\nsafari 6.0.2","closed_by":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false}}