{"url":"https://api.github.com/repos/owncloud/core/issues/4939","labels_url":"https://api.github.com/repos/owncloud/core/issues/4939/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/4939/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/4939/events","html_url":"https://github.com/owncloud/core/issues/4939","id":19875580,"number":4939,"title":"client unknown status, client shows wrong status of synchronization, it is not possible to recover synchronization","user":{"login":"jozefcernak","id":5513484,"avatar_url":"https://gravatar.com/avatar/072476466f53122cacc8f6fc4c384bbf?d=https%3a%2f%2fidenticons.github.com%2ffa6e1586ac644a3cf9a7a75782af4e36.png&r=x","gravatar_id":"072476466f53122cacc8f6fc4c384bbf","url":"https://api.github.com/users/jozefcernak","html_url":"https://github.com/jozefcernak","followers_url":"https://api.github.com/users/jozefcernak/followers","following_url":"https://api.github.com/users/jozefcernak/following{/other_user}","gists_url":"https://api.github.com/users/jozefcernak/gists{/gist_id}","starred_url":"https://api.github.com/users/jozefcernak/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jozefcernak/subscriptions","organizations_url":"https://api.github.com/users/jozefcernak/orgs","repos_url":"https://api.github.com/users/jozefcernak/repos","events_url":"https://api.github.com/users/jozefcernak/events{/privacy}","received_events_url":"https://api.github.com/users/jozefcernak/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":2,"created_at":"2013-09-22t17:02:02z","updated_at":"2013-09-22t19:25:23z","closed_at":"2013-09-22t19:25:23z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"hi,\r\n\r\ni initially i started client it worked nice. i tried to add a few files it still worked. however i added about 2000 files totally 5gb directory in local owncloud directory. synchronization started and continued up 1gb then\r\nclient stopped to wok i got unknown status, \r\ni tried to interrupt synchronization (setting-pause) and  client stopped works. my feeling is that client is not able to start synchronization again.\r\n\r\nin addition icon shows that directory is synchronized which really false information. i checked server side where many of files are not copied.\r\n\r\nwww interface works\r\n\r\njozef\r\n\r\nos ubuntu 12.04, gnome,\r\nclient from your repository \r\n\r\nthe latest version of client and server","closed_by":{"login":"kabum","id":245432,"avatar_url":"https://gravatar.com/avatar/a1dea19f88f38ea0b5b5b4d19d5b3107?d=https%3a%2f%2fidenticons.github.com%2f53d8cbb3dbc087a02951dec47438ccdf.png&r=x","gravatar_id":"a1dea19f88f38ea0b5b5b4d19d5b3107","url":"https://api.github.com/users/kabum","html_url":"https://github.com/kabum","followers_url":"https://api.github.com/users/kabum/followers","following_url":"https://api.github.com/users/kabum/following{/other_user}","gists_url":"https://api.github.com/users/kabum/gists{/gist_id}","starred_url":"https://api.github.com/users/kabum/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kabum/subscriptions","organizations_url":"https://api.github.com/users/kabum/orgs","repos_url":"https://api.github.com/users/kabum/repos","events_url":"https://api.github.com/users/kabum/events{/privacy}","received_events_url":"https://api.github.com/users/kabum/received_events","type":"user","site_admin":false}}