{"url":"https://api.github.com/repos/owncloud/core/issues/3195","labels_url":"https://api.github.com/repos/owncloud/core/issues/3195/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/3195/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/3195/events","html_url":"https://github.com/owncloud/core/issues/3195","id":13807495,"number":3195,"title":"credentials error after upgrading the server to 5.0.5","user":{"login":"rperezb","id":1846927,"avatar_url":"https://gravatar.com/avatar/b4ad2bf83a0aabe434d87d674a6a01c0?d=https%3a%2f%2fidenticons.github.com%2f726ebac89cf4616e7506f7abfd8bc43d.png&r=x","gravatar_id":"b4ad2bf83a0aabe434d87d674a6a01c0","url":"https://api.github.com/users/rperezb","html_url":"https://github.com/rperezb","followers_url":"https://api.github.com/users/rperezb/followers","following_url":"https://api.github.com/users/rperezb/following{/other_user}","gists_url":"https://api.github.com/users/rperezb/gists{/gist_id}","starred_url":"https://api.github.com/users/rperezb/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rperezb/subscriptions","organizations_url":"https://api.github.com/users/rperezb/orgs","repos_url":"https://api.github.com/users/rperezb/repos","events_url":"https://api.github.com/users/rperezb/events{/privacy}","received_events_url":"https://api.github.com/users/rperezb/received_events","type":"user","site_admin":false},"labels":[{"url":"https://api.github.com/repos/owncloud/core/labels/needs+info","name":"needs info","color":"0b02e1"}],"state":"closed","assignee":null,"milestone":null,"comments":3,"created_at":"2013-04-30t13:57:45z","updated_at":"2013-05-06t11:13:17z","closed_at":"2013-05-06t11:13:17z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"after upgrading the server to 5.0.5 some users are having a credential error problem on the ios app, although they enter the right user and password.\r\n\r\nfrom here, it has been not possible to reproduce the error.\r\n\r\nhowever, some users have provided me user account on their servers and iâ´ve been able to reproduce the error. \r\n\r\nwhat i noticed is that with a web browser and cleaning the cache,, we access to the url: server/remote.php/webdav\r\n\r\nit is required to log in, by entering the right credentials , it is always received a credentials error, by cancelling the operation it is shown:\r\n\r\n\"sabre_dav_exception_notauthenticated no basic authentication headers were found 1.7.6\"\r\n\r\n","closed_by":{"login":"rperezb","id":1846927,"avatar_url":"https://gravatar.com/avatar/b4ad2bf83a0aabe434d87d674a6a01c0?d=https%3a%2f%2fidenticons.github.com%2f726ebac89cf4616e7506f7abfd8bc43d.png&r=x","gravatar_id":"b4ad2bf83a0aabe434d87d674a6a01c0","url":"https://api.github.com/users/rperezb","html_url":"https://github.com/rperezb","followers_url":"https://api.github.com/users/rperezb/followers","following_url":"https://api.github.com/users/rperezb/following{/other_user}","gists_url":"https://api.github.com/users/rperezb/gists{/gist_id}","starred_url":"https://api.github.com/users/rperezb/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rperezb/subscriptions","organizations_url":"https://api.github.com/users/rperezb/orgs","repos_url":"https://api.github.com/users/rperezb/repos","events_url":"https://api.github.com/users/rperezb/events{/privacy}","received_events_url":"https://api.github.com/users/rperezb/received_events","type":"user","site_admin":false}}