{"url":"https://api.github.com/repos/owncloud/core/issues/1104","labels_url":"https://api.github.com/repos/owncloud/core/issues/1104/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/1104/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/1104/events","html_url":"https://github.com/owncloud/core/issues/1104","id":9719040,"number":1104,"title":"problem with omnifocus and owncloud","user":{"login":"lihamakaroonilaatikko","id":3200312,"avatar_url":"https://gravatar.com/avatar/d0f3a02dc59afadffeb05a0171c51bc4?d=https%3a%2f%2fidenticons.github.com%2f0eb9f234880a950a8ce07eaea84a6979.png&r=x","gravatar_id":"d0f3a02dc59afadffeb05a0171c51bc4","url":"https://api.github.com/users/lihamakaroonilaatikko","html_url":"https://github.com/lihamakaroonilaatikko","followers_url":"https://api.github.com/users/lihamakaroonilaatikko/followers","following_url":"https://api.github.com/users/lihamakaroonilaatikko/following{/other_user}","gists_url":"https://api.github.com/users/lihamakaroonilaatikko/gists{/gist_id}","starred_url":"https://api.github.com/users/lihamakaroonilaatikko/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/lihamakaroonilaatikko/subscriptions","organizations_url":"https://api.github.com/users/lihamakaroonilaatikko/orgs","repos_url":"https://api.github.com/users/lihamakaroonilaatikko/repos","events_url":"https://api.github.com/users/lihamakaroonilaatikko/events{/privacy}","received_events_url":"https://api.github.com/users/lihamakaroonilaatikko/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":6,"created_at":"2013-01-06t18:53:03z","updated_at":"2013-11-01t22:13:57z","closed_at":"2013-02-09t14:56:03z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"i'm having problems with syncing omnifocus with owncloud 4.5.x. the error is \"error while writing file(/<username>/files/omnifocus.ofocus-copy-in-progress-kthkps68f52/20130106184316=dy1cnrycljx.client-write-in-progress-bfiulwin0j7) to cache\". the sync worked and still works with 4.0.x. something changed with webdav interface between 4.5 and 4.0. changing logging from warning to debug did not give more information.","closed_by":{"login":"karlitschek","id":867445,"avatar_url":"https://gravatar.com/avatar/87ce2b4531ee1a0c32b50e0d8f049224?d=https%3a%2f%2fidenticons.github.com%2f06e7098636caebfc9c30c9f52eb905df.png&r=x","gravatar_id":"87ce2b4531ee1a0c32b50e0d8f049224","url":"https://api.github.com/users/karlitschek","html_url":"https://github.com/karlitschek","followers_url":"https://api.github.com/users/karlitschek/followers","following_url":"https://api.github.com/users/karlitschek/following{/other_user}","gists_url":"https://api.github.com/users/karlitschek/gists{/gist_id}","starred_url":"https://api.github.com/users/karlitschek/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/karlitschek/subscriptions","organizations_url":"https://api.github.com/users/karlitschek/orgs","repos_url":"https://api.github.com/users/karlitschek/repos","events_url":"https://api.github.com/users/karlitschek/events{/privacy}","received_events_url":"https://api.github.com/users/karlitschek/received_events","type":"user","site_admin":false}}