{"url":"https://api.github.com/repos/owncloud/core/issues/643","labels_url":"https://api.github.com/repos/owncloud/core/issues/643/labels{/name}","comments_url":"https://api.github.com/repos/owncloud/core/issues/643/comments","events_url":"https://api.github.com/repos/owncloud/core/issues/643/events","html_url":"https://github.com/owncloud/core/issues/643","id":8851535,"number":643,"title":"since lient update to client 1.12 connection to server claims times out error","user":{"login":"docml","id":2471116,"avatar_url":"https://gravatar.com/avatar/304d56a20ce2082ce8a7a7a8885c182a?d=https%3a%2f%2fidenticons.github.com%2f419d4e4a1b1ba1b1a1fdb951a1142b50.png&r=x","gravatar_id":"304d56a20ce2082ce8a7a7a8885c182a","url":"https://api.github.com/users/docml","html_url":"https://github.com/docml","followers_url":"https://api.github.com/users/docml/followers","following_url":"https://api.github.com/users/docml/following{/other_user}","gists_url":"https://api.github.com/users/docml/gists{/gist_id}","starred_url":"https://api.github.com/users/docml/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/docml/subscriptions","organizations_url":"https://api.github.com/users/docml/orgs","repos_url":"https://api.github.com/users/docml/repos","events_url":"https://api.github.com/users/docml/events{/privacy}","received_events_url":"https://api.github.com/users/docml/received_events","type":"user","site_admin":false},"labels":[],"state":"closed","assignee":null,"milestone":null,"comments":1,"created_at":"2012-11-30t10:32:01z","updated_at":"2012-11-30t10:36:24z","closed_at":"2012-11-30t10:36:24z","pull_request":{"html_url":null,"diff_url":null,"patch_url":null},"body":"hi, \n\ni was running owncloud 4.5.2 with the mac and windows client 1.1.1 and everything worked.\ni recently updated to owncloud 4.5.3 and client 1.1.2 and the sync via client does not work anymore it claims a connection or proxy error.\nit happens with both windows and osx client.\nis there a chance that i can download the client 1.1.1 again since that seemed to work.\nin general it would be nice to have at least the last version of a client also online for downloading in case such errors occur.","closed_by":{"login":"deepdiver1975","id":1005065,"avatar_url":"https://gravatar.com/avatar/bdba071ed68da9ce8edae53c364902ef?d=https%3a%2f%2fidenticons.github.com%2f67e101ad9531b7d25697b76e503e062e.png&r=x","gravatar_id":"bdba071ed68da9ce8edae53c364902ef","url":"https://api.github.com/users/deepdiver1975","html_url":"https://github.com/deepdiver1975","followers_url":"https://api.github.com/users/deepdiver1975/followers","following_url":"https://api.github.com/users/deepdiver1975/following{/other_user}","gists_url":"https://api.github.com/users/deepdiver1975/gists{/gist_id}","starred_url":"https://api.github.com/users/deepdiver1975/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/deepdiver1975/subscriptions","organizations_url":"https://api.github.com/users/deepdiver1975/orgs","repos_url":"https://api.github.com/users/deepdiver1975/repos","events_url":"https://api.github.com/users/deepdiver1975/events{/privacy}","received_events_url":"https://api.github.com/users/deepdiver1975/received_events","type":"user","site_admin":false}}